var CK = ctx.CanvasKit;
var c = ctx.getCanvas();
c.clear(CK.parseColorString('#020617'));
var p = new CK.Paint();
p.setStyle(CK.PaintStyle.Fill);
var S = 142;
for (var i = 0; i < 35; i++) {
  p.setColor(CK.Color4f(1, 1, 1, ctx.utils.random(0.15, 0.5, S + i * 5 + 3)));
  c.drawCircle(ctx.utils.random(0, 780, S + i * 5), ctx.utils.random(0, 680, S + i * 5 + 1), ctx.utils.random(0.5, 2.0, S + i * 5 + 2), p);
}
var cx = 340, cy = 340, rx = 260, ry = 170, foc = Math.sqrt(rx * rx - ry * ry);
var fx = cx - foc, fy = cy;
var op = new CK.Paint();
op.setStyle(CK.PaintStyle.Stroke);
op.setStrokeWidth(2);
op.setColor(CK.parseColorString('#22d3ee'));
op.setAntiAlias(true);
c.drawOval(CK.XYWHRect(cx - rx, cy - ry, rx * 2, ry * 2), op);
var fp = new CK.Paint();
fp.setStyle(CK.PaintStyle.Stroke);
fp.setStrokeWidth(1.5);
fp.setColor(CK.parseColorString('#cbd5e1'));
c.drawLine(fx - 10, fy, fx + 10, fy, fp);
c.drawLine(fx, fy - 10, fx, fy + 10, fp);
var sp = new CK.Paint();
sp.setStyle(CK.PaintStyle.Fill);
var glow = 0.12 + 0.04 * Math.sin(ctx.currentFrame * 0.03);
sp.setColor(CK.Color4f(0.98, 0.76, 0.14, glow));
c.drawCircle(fx, fy, 38, sp);
sp.setColor(CK.parseColorString('#fbbf24'));
c.drawCircle(fx, fy, 22, sp);
var theta = (ctx.currentFrame / ctx.sceneFrames) * 2 * Math.PI;
var px = cx + rx * Math.cos(theta);
var py = cy + ry * Math.sin(theta);
var tp = new CK.Paint();
tp.setStyle(CK.PaintStyle.Stroke);
tp.setStrokeWidth(2);
tp.setColor(CK.Color4f(0.13, 0.83, 0.93, 0.25));
tp.setAntiAlias(true);
c.drawArc(CK.XYWHRect(cx - rx, cy - ry, rx * 2, ry * 2), -90, (theta * 180 / Math.PI), false, tp);
var pp = new CK.Paint();
pp.setStyle(CK.PaintStyle.Fill);
pp.setColor(CK.WHITE);
c.drawCircle(px, py, 8, pp);
