// ---------------------------------------------------------------------------
// OCIR schema → TypeScript code generator
//
// Reads the canonical constants in draw_encoding and produces a self-contained
// TypeScript module that the Web decoder imports.  The generated file is
// checked in under web/src/generated/ so that the Rust-free web build can
// consume it.  A compilation-time test ensures the checked-in file matches
// whatever would be generated today — drift trips CI.
// ---------------------------------------------------------------------------

use super::draw_encoding::{IR_VERSION, section, opcode};

/// Return the complete TypeScript source for the OCIR wire-protocol constants
/// and canonical enum mappings.
pub fn generate_ocir_schema_ts() -> String {
    let mut ts = String::new();

    header(&mut ts);
    ts.push('\n');
    magic_version(&mut ts);
    ts.push('\n');
    section_constants(&mut ts);
    ts.push('\n');
    opcode_constants(&mut ts);
    ts.push('\n');
    path_op_sub_constants(&mut ts);
    ts.push('\n');
    enum_constants(&mut ts);

    ts
}

// ---------------------------------------------------------------------------
// Sections of the generated file
// ---------------------------------------------------------------------------

fn header(ts: &mut String) {
    ts.push_str(
        "// @generated by opencat-core schema_gen.rs — do not edit.\n\
         // Source: crates/opencat-core/src/ir/draw_encoding.rs\n\
         //\n\
         // Re-generate with: cargo test -p opencat-core write_ocir_schema\n",
    );
}

fn magic_version(ts: &mut String) {
    use std::fmt::Write;
    ts.push_str(
        "// ---------------------------------------------------------------------------\n\
         // OCIR magic + version\n\
         // ---------------------------------------------------------------------------\n\n\
         /// Magic bytes for the OCIR envelope: \"OCIR\".\n\
         export const IR_MAGIC: [number, number, number, number] = [0x4f, 0x43, 0x49, 0x52];\n\n\
         /// Wire protocol version (must match [super::draw_encoding::IR_VERSION]).\n\
         export const IR_VERSION: number = ",
    );
    let _ = write!(ts, "{}", IR_VERSION);
    ts.push_str(";\n");
}

fn section_constants(ts: &mut String) {
    use std::fmt::Write;
    ts.push_str(
        "// ---------------------------------------------------------------------------\n\
         // Section identifiers in the OCIR directory\n\
         // ---------------------------------------------------------------------------\n\n\
         export const SECTION = {\n",
    );
    for (name, id) in &[
        ("OPS", section::OPS),
        ("F32_POOL", section::F32_POOL),
        ("BYTES", section::BYTES),
        ("BYTE_RANGES", section::BYTE_RANGES),
        ("STRINGS_UTF8", section::STRINGS_UTF8),
        ("STRING_RANGES", section::STRING_RANGES),
        ("PAINTS", section::PAINTS),
        ("PATHS", section::PATHS),
        ("CHILDREN", section::CHILDREN),
        ("EFFECTS", section::EFFECTS),
        ("SUBTREES", section::SUBTREES),
        ("GENERATED_IMAGES", section::GENERATED_IMAGES),
    ] {
        let _ = write!(ts, "    {}: {},\n", name, id);
    }
    ts.push_str(
        "} as const;\n\
         \n\
         export type SectionId = (typeof SECTION)[keyof typeof SECTION];\n",
    );
}

fn opcode_constants(ts: &mut String) {
    use std::fmt::Write;
    ts.push_str(
        "// ---------------------------------------------------------------------------\n\
         // DrawOp opcode assignments — each variant gets a unique u16.\n\
         // ---------------------------------------------------------------------------\n\n\
         export const OP = {\n",
    );
    for (name, value) in &[
        ("SAVE", opcode::SAVE),
        ("SAVE_LAYER", opcode::SAVE_LAYER),
        ("RESTORE", opcode::RESTORE),
        ("RESTORE_TO_COUNT", opcode::RESTORE_TO_COUNT),
        ("TRANSLATE", opcode::TRANSLATE),
        ("SCALE", opcode::SCALE),
        ("ROTATE", opcode::ROTATE),
        ("SKEW", opcode::SKEW),
        ("CONCAT", opcode::CONCAT),
        ("SET_FILL_STYLE", opcode::SET_FILL_STYLE),
        ("SET_STROKE_STYLE", opcode::SET_STROKE_STYLE),
        ("SET_LINE_WIDTH", opcode::SET_LINE_WIDTH),
        ("SET_LINE_CAP", opcode::SET_LINE_CAP),
        ("SET_LINE_JOIN", opcode::SET_LINE_JOIN),
        ("SET_LINE_DASH", opcode::SET_LINE_DASH),
        ("CLEAR_LINE_DASH", opcode::CLEAR_LINE_DASH),
        ("SET_GLOBAL_ALPHA", opcode::SET_GLOBAL_ALPHA),
        ("SET_ANTI_ALIAS", opcode::SET_ANTI_ALIAS),
        ("BEGIN_PATH", opcode::BEGIN_PATH),
        ("PATH_OP", opcode::PATH_OP),
        ("FILL_PATH", opcode::FILL_PATH),
        ("STROKE_PATH", opcode::STROKE_PATH),
        ("CLIP_PATH", opcode::CLIP_PATH),
        ("CLEAR", opcode::CLEAR),
        ("PAINT", opcode::PAINT),
        ("RECT", opcode::RECT),
        ("R_RECT", opcode::R_RECT),
        ("D_RRECT", opcode::D_RRECT),
        ("OVAL", opcode::OVAL),
        ("CIRCLE", opcode::CIRCLE),
        ("ARC", opcode::ARC),
        ("LINE", opcode::LINE),
        ("POINTS", opcode::POINTS),
        ("DRAW_PATH", opcode::DRAW_PATH),
        ("IMAGE", opcode::IMAGE),
        ("IMAGE_RECT", opcode::IMAGE_RECT),
        ("RUNTIME_EFFECT", opcode::RUNTIME_EFFECT),
        ("REPLAY_RANGE", opcode::REPLAY_RANGE),
        ("DRAW_SUBTREE_PICTURE", opcode::DRAW_SUBTREE_PICTURE),
        ("LOTTIE_RECT", opcode::LOTTIE_RECT),
    ] {
        let _ = write!(ts, "    {}: {},\n", name, value);
    }
    ts.push_str(
        "} as const;\n\
         \n\
         export type Opcode = (typeof OP)[keyof typeof OP];\n",
    );
}

fn path_op_sub_constants(ts: &mut String) {
    use std::fmt::Write;
    ts.push_str(
        "// ---------------------------------------------------------------------------\n\
         // PathOp sub-opcodes (embedded in PATH_OP payload)\n\
         // ---------------------------------------------------------------------------\n\n\
         export const PATH_OP_SUB = {\n",
    );
    for (name, value) in &[
        ("MOVE_TO", opcode::PATH_MOVE_TO),
        ("LINE_TO", opcode::PATH_LINE_TO),
        ("QUAD_TO", opcode::PATH_QUAD_TO),
        ("CUBIC_TO", opcode::PATH_CUBIC_TO),
        ("CLOSE", opcode::PATH_CLOSE),
        ("ADD_RECT", opcode::PATH_ADD_RECT),
        ("ADD_RRECT", opcode::PATH_ADD_RRECT),
        ("ADD_OVAL", opcode::PATH_ADD_OVAL),
        ("ADD_ARC", opcode::PATH_ADD_ARC),
    ] {
        let _ = write!(ts, "    {}: {},\n", name, value);
    }
    ts.push_str(
        "} as const;\n\
         \n\
         /// Number of f32 values for each PathOp sub-opcode by its stored kind.\n\
         /// Indexed by PATH_OP_SUB value.\n\
         export const PATH_OP_F32_WIDTHS: readonly number[] = [",
    );
    for (i, w) in opcode::PATH_OP_F32_WIDTHS.iter().enumerate() {
        if i > 0 {
            ts.push_str(", ");
        }
        let _ = write!(ts, "{}", w);
    }
    ts.push_str(
        "];\n\
         \n\
         export type PathOpSub = (typeof PATH_OP_SUB)[keyof typeof PATH_OP_SUB];\n",
    );
}

fn enum_constants(ts: &mut String) {
    use std::fmt::Write;
    use super::draw_encoding::{
        encode_blend_mode, encode_blur_style, encode_line_cap, encode_line_join,
        encode_path_fill_type, encode_point_mode, encode_stroke_cap, encode_stroke_join,
        encode_tile_mode,
    };
    use crate::canvas::paint::{BlendMode, BlurStyle, PaintStyle as CkPaintStyle, StrokeCap, StrokeJoin, TileMode};
    use super::draw_op::{LineCap, LineJoin, PointMode};
    use super::draw_types::FillType;

    ts.push_str(
        "// ---------------------------------------------------------------------------\n\
         // Wire enum encodings (must match core encode_* helpers)\n\
         // ---------------------------------------------------------------------------\n\n",
    );

    // LineCap
    let _ = write!(ts,
        "/// Line cap wire encoding: 0=Butt, 1=Round, 2=Square.\n\
         export const LINE_CAP = {{ BUTT: {}, ROUND: {}, SQUARE: {} }} as const;\n\
         export type LineCap = (typeof LINE_CAP)[keyof typeof LINE_CAP];\n\n",
        encode_line_cap(LineCap::Butt),
        encode_line_cap(LineCap::Round),
        encode_line_cap(LineCap::Square),
    );

    // LineJoin
    let _ = write!(ts,
        "/// Line join wire encoding: 0=Miter, 1=Round, 2=Bevel.\n\
         export const LINE_JOIN = {{ MITER: {}, ROUND: {}, BEVEL: {} }} as const;\n\
         export type LineJoin = (typeof LINE_JOIN)[keyof typeof LINE_JOIN];\n\n",
        encode_line_join(LineJoin::Miter),
        encode_line_join(LineJoin::Round),
        encode_line_join(LineJoin::Bevel),
    );

    // PointMode
    let _ = write!(ts,
        "/// Point mode wire encoding: 0=Points, 1=Lines, 2=Polygon.\n\
         export const POINT_MODE = {{ POINTS: {}, LINES: {}, POLYGON: {} }} as const;\n\
         export type PointMode = (typeof POINT_MODE)[keyof typeof POINT_MODE];\n\n",
        encode_point_mode(PointMode::Points),
        encode_point_mode(PointMode::Lines),
        encode_point_mode(PointMode::Polygon),
    );

    // PaintStyle
    let _ = write!(ts,
        "/// Paint style wire encoding: 0=Fill, 1=Stroke.\n\
         export const PAINT_STYLE = {{ FILL: {}, STROKE: {} }} as const;\n\
         export type PaintStyle = (typeof PAINT_STYLE)[keyof typeof PAINT_STYLE];\n\n",
        super::draw_encoding::encode_paint_style(CkPaintStyle::Fill),
        super::draw_encoding::encode_paint_style(CkPaintStyle::Stroke),
    );

    // StrokeCap
    let _ = write!(ts,
        "/// Stroke cap wire encoding: 0=Butt, 1=Round, 2=Square.\n\
         export const STROKE_CAP = {{ BUTT: {}, ROUND: {}, SQUARE: {} }} as const;\n\
         export type StrokeCap = (typeof STROKE_CAP)[keyof typeof STROKE_CAP];\n\n",
        encode_stroke_cap(StrokeCap::Butt),
        encode_stroke_cap(StrokeCap::Round),
        encode_stroke_cap(StrokeCap::Square),
    );

    // StrokeJoin
    let _ = write!(ts,
        "/// Stroke join wire encoding: 0=Miter, 1=Round, 2=Bevel.\n\
         export const STROKE_JOIN = {{ MITER: {}, ROUND: {}, BEVEL: {} }} as const;\n\
         export type StrokeJoin = (typeof STROKE_JOIN)[keyof typeof STROKE_JOIN];\n\n",
        encode_stroke_join(StrokeJoin::Miter),
        encode_stroke_join(StrokeJoin::Round),
        encode_stroke_join(StrokeJoin::Bevel),
    );

    // BlendMode
    ts.push_str("/// Blend mode wire encoding.\n");
    ts.push_str("export const BLEND_MODE = {\n");
    for (name, mode) in &[
        ("CLEAR", BlendMode::Clear),
        ("SRC", BlendMode::Src),
        ("DST", BlendMode::Dst),
        ("SRC_OVER", BlendMode::SrcOver),
        ("DST_OVER", BlendMode::DstOver),
        ("SRC_IN", BlendMode::SrcIn),
        ("DST_IN", BlendMode::DstIn),
        ("SRC_OUT", BlendMode::SrcOut),
        ("DST_OUT", BlendMode::DstOut),
        ("SRC_A_TOP", BlendMode::SrcATop),
        ("DST_A_TOP", BlendMode::DstATop),
        ("XOR", BlendMode::Xor),
        ("PLUS", BlendMode::Plus),
        ("MODULATE", BlendMode::Modulate),
        ("SCREEN", BlendMode::Screen),
        ("OVERLAY", BlendMode::Overlay),
        ("DARKEN", BlendMode::Darken),
        ("LIGHTEN", BlendMode::Lighten),
        ("COLOR_DODGE", BlendMode::ColorDodge),
        ("COLOR_BURN", BlendMode::ColorBurn),
        ("HARD_LIGHT", BlendMode::HardLight),
        ("SOFT_LIGHT", BlendMode::SoftLight),
        ("DIFFERENCE", BlendMode::Difference),
        ("EXCLUSION", BlendMode::Exclusion),
        ("MULTIPLY", BlendMode::Multiply),
        ("HUE", BlendMode::Hue),
        ("SATURATION", BlendMode::Saturation),
        ("COLOR", BlendMode::Color),
        ("LUMINOSITY", BlendMode::Luminosity),
    ] {
        let _ = write!(ts, "    {}: {},\n", name, encode_blend_mode(*mode));
    }
    ts.push_str(
        "} as const;\n\
         export type BlendMode = (typeof BLEND_MODE)[keyof typeof BLEND_MODE];\n\n",
    );

    // TileMode
    let _ = write!(ts,
        "/// Tile mode wire encoding: 0=Clamp, 1=Repeat, 2=Mirror, 3=Decal.\n\
         export const TILE_MODE = {{ CLAMP: {}, REPEAT: {}, MIRROR: {}, DECAL: {} }} as const;\n\
         export type TileMode = (typeof TILE_MODE)[keyof typeof TILE_MODE];\n\n",
        encode_tile_mode(TileMode::Clamp),
        encode_tile_mode(TileMode::Repeat),
        encode_tile_mode(TileMode::Mirror),
        encode_tile_mode(TileMode::Decal),
    );

    // BlurStyle
    let _ = write!(ts,
        "/// Blur style wire encoding: 0=Normal, 1=Inner, 2=Solid, 3=Outer.\n\
         export const BLUR_STYLE = {{ NORMAL: {}, INNER: {}, SOLID: {}, OUTER: {} }} as const;\n\
         export type BlurStyle = (typeof BLUR_STYLE)[keyof typeof BLUR_STYLE];\n\n",
        encode_blur_style(BlurStyle::Normal),
        encode_blur_style(BlurStyle::Inner),
        encode_blur_style(BlurStyle::Solid),
        encode_blur_style(BlurStyle::Outer),
    );

    // FillType
    let _ = write!(ts,
        "/// Path fill type wire encoding: 0=Winding, 1=EvenOdd.\n\
         export const FILL_TYPE = {{ WINDING: {}, EVEN_ODD: {} }} as const;\n\
         export type FillType = (typeof FILL_TYPE)[keyof typeof FILL_TYPE];\n\n",
        encode_path_fill_type(FillType::Winding),
        encode_path_fill_type(FillType::EvenOdd),
    );

    // ImageRef tag — not backed by an encode function, hardcoded in encoder logic.
    ts.push_str(
        "/// ImageRef tag wire encoding: 0=Static, 1=VideoFrame, 2=Generated.\n\
         export const IMAGE_REF_TAG = { STATIC: 0, VIDEO_FRAME: 1, GENERATED: 2 } as const;\n\
         export type ImageRefTag = (typeof IMAGE_REF_TAG)[keyof typeof IMAGE_REF_TAG];\n\n",
    );

    // ChildRef kind — not backed by an encode function, hardcoded in encoder logic.
    ts.push_str(
        "/// ChildRef kind wire encoding: 0=Image, 1=Picture, 2=Shader, 3=SubtreePicture.\n\
         export const CHILD_REF_KIND = { IMAGE: 0, PICTURE: 1, SHADER: 2, SUBTREE_PICTURE: 3 } as const;\n\
         export type ChildRefKind = (typeof CHILD_REF_KIND)[keyof typeof CHILD_REF_KIND];\n",
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// Package decoder path (rootDir-safe for crates/opencat-web/web tsc).
    const PACKAGE_GENERATED_DIR: &str = "../opencat-web/web/src/generated";
    /// Web app test path (draw-ir.test.ts imports from here).
    const WEB_GENERATED_DIR: &str = "../../web/src/generated";
    const GENERATED_FILE: &str = "ocir-schema.generated.ts";

    fn generated_paths() -> [String; 2] {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        [
            root.join(PACKAGE_GENERATED_DIR)
                .join(GENERATED_FILE)
                .to_string_lossy()
                .into_owned(),
            root.join(WEB_GENERATED_DIR)
                .join(GENERATED_FILE)
                .to_string_lossy()
                .into_owned(),
        ]
    }

    // -----------------------------------------------------------------------
    // Schema drift — CI bouncer
    // -----------------------------------------------------------------------

    /// Assert that every checked-in generated file is up to date with the core
    /// canonical constants.  If this fails, re-run the `write_ocir_schema` test
    /// below to regenerate them.
    #[test]
    fn ocir_schema_generated_file_is_up_to_date() {
        let current = generate_ocir_schema_ts();
        for path in generated_paths() {
            let generated = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Generated file not found at {path}: {e}"));
            assert_eq!(
                generated, current,
                "\n\
                 OCIR TypeScript schema is out of date with core canonical constants.\n\
                 Path: {path}\n\
                 \n\
                 To regenerate:\n\
                   cargo test -p opencat-core write_ocir_schema -- --ignored\n\
                 \n\
                 Then commit the updated files:\n\
                   git add crates/opencat-web/web/src/generated/ocir-schema.generated.ts \\\n\
                           web/src/generated/ocir-schema.generated.ts\n\
                 \n\
                 If the schema changed intentionally, this is expected.\n\
                 If you see this in CI, the PR author forgot to re-run the generator.\n",
            );
        }
    }

    // -----------------------------------------------------------------------
    // Write — run manually or on `-- --ignored` to regenerate
    // -----------------------------------------------------------------------

    /// Write the generated TypeScript file to package + web-app paths.  Run this
    /// when core canonical constants change so that the Web build stays in sync.
    ///
    /// This test is `#[ignore]`d by default so it doesn't write to the source
    /// tree on every `cargo test`.  Run it explicitly:
    ///
    ///   cargo test -p opencat-core write_ocir_schema -- --ignored
    #[test]
    #[ignore]
    fn write_ocir_schema() {
        let ts = generate_ocir_schema_ts();
        for path in generated_paths() {
            let dir = Path::new(&path).parent().unwrap();
            std::fs::create_dir_all(dir)
                .unwrap_or_else(|e| panic!("failed to create {dir:?}: {e}"));

            std::fs::write(&path, &ts)
                .unwrap_or_else(|e| panic!("failed to write {path}: {e}"));

            // Sanity: re-read matches.
            let reread = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to re-read {path}: {e}"));
            assert_eq!(reread, ts, "written file must be byte-identical: {path}");

            eprintln!("OCIR schema written to {path}");
        }
    }
}
