pub mod backend;
pub mod composition;
pub mod display;
pub mod element;
pub mod frame_ctx;
pub mod layout;
pub mod media;
pub mod nodes;
pub mod render;
pub mod style;
pub mod transitions;
pub mod typography;
pub mod view;

pub use composition::Composition;
pub use frame_ctx::FrameCtx;
pub use nodes::{div, image, text, video};
pub use opencat_macros::component;
pub use render::EncodingConfig;
pub use transitions::{TransitionSeries, light_leak, linear, slide, transition_series};
pub use view::{Node, ViewNode, component_node, component_node_with_duration};
